
package com.seotandil.ws.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.0.4
 * Sat Apr 25 18:43:25 GFT 2015
 * Generated source version: 3.0.4
 */

@XmlRootElement(name = "guardarSegmento", namespace = "http://ws.seotandil.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "guardarSegmento", namespace = "http://ws.seotandil.com/")

public class GuardarSegmento {

    @XmlElement(name = "arg0")
    private com.seotandil.dto.Segmento arg0;

    public com.seotandil.dto.Segmento getArg0() {
        return this.arg0;
    }

    public void setArg0(com.seotandil.dto.Segmento newArg0)  {
        this.arg0 = newArg0;
    }

}

