
package com.seotandil.ws.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.0.4
 * Sat Apr 25 18:43:25 GFT 2015
 * Generated source version: 3.0.4
 */

@XmlRootElement(name = "obtenerEdges", namespace = "http://ws.seotandil.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "obtenerEdges", namespace = "http://ws.seotandil.com/")

public class ObtenerEdges {


}

