
package com.seotandil.ws.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.0.4
 * Sat Apr 25 18:43:25 GFT 2015
 * Generated source version: 3.0.4
 */

@XmlRootElement(name = "obtenerSegmento", namespace = "http://ws.seotandil.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "obtenerSegmento", namespace = "http://ws.seotandil.com/", propOrder = {"arg0", "arg1"})

public class ObtenerSegmento {

    @XmlElement(name = "arg0")
    private int arg0;
    @XmlElement(name = "arg1")
    private boolean arg1;

    public int getArg0() {
        return this.arg0;
    }

    public void setArg0(int newArg0)  {
        this.arg0 = newArg0;
    }

    public boolean getArg1() {
        return this.arg1;
    }

    public void setArg1(boolean newArg1)  {
        this.arg1 = newArg1;
    }

}

