
package com.seotandil.ws.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.0.4
 * Sat Apr 25 18:43:25 GFT 2015
 * Generated source version: 3.0.4
 */

@XmlRootElement(name = "httpRequest", namespace = "http://ws.seotandil.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "httpRequest", namespace = "http://ws.seotandil.com/", propOrder = {"arg0", "arg1"})

public class HttpRequest {

    @XmlElement(name = "arg0")
    private java.lang.String arg0;
    @XmlElement(name = "arg1")
    private com.seotandil.dto.Segmento arg1;

    public java.lang.String getArg0() {
        return this.arg0;
    }

    public void setArg0(java.lang.String newArg0)  {
        this.arg0 = newArg0;
    }

    public com.seotandil.dto.Segmento getArg1() {
        return this.arg1;
    }

    public void setArg1(com.seotandil.dto.Segmento newArg1)  {
        this.arg1 = newArg1;
    }

}

