
package com.seotandil.ws.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.0.4
 * Sat Apr 25 18:43:25 GFT 2015
 * Generated source version: 3.0.4
 */

@XmlRootElement(name = "obtenerNodesResponse", namespace = "http://ws.seotandil.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "obtenerNodesResponse", namespace = "http://ws.seotandil.com/")

public class ObtenerNodesResponse {

    @XmlElement(name = "return")
    private java.util.List<com.seotandil.dto.Node> _return;

    public java.util.List<com.seotandil.dto.Node> getReturn() {
        return this._return;
    }

    public void setReturn(java.util.List<com.seotandil.dto.Node> new_return)  {
        this._return = new_return;
    }

}

