package com.seotandil.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.4
 * 2015-04-09T19:57:04.529-03:00
 * Generated source version: 3.0.4
 * 
 */
@WebServiceClient(name = "SeoTandilServicesService", 
                  wsdlLocation = "http://localhost:8080/SeoTandilWS/services/seotandilservices?wsdl",
                  targetNamespace = "http://ws.seotandil.com/") 
public class SeoTandilServices extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://ws.seotandil.com/", "SeoTandilServicesService");
    public final static QName SeoTandilServicesPort = new QName("http://ws.seotandil.com/", "SeoTandilServicesPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/SeoTandilWS/services/seotandilservices?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(SeoTandilServices.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/SeoTandilWS/services/seotandilservices?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public SeoTandilServices(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SeoTandilServices(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SeoTandilServices() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SeoTandilServices(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SeoTandilServices(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SeoTandilServices(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns ISeoTandilServices
     */
    @WebEndpoint(name = "SeoTandilServicesPort")
    public ISeoTandilServices getSeoTandilServicesPort() {
        return super.getPort(SeoTandilServicesPort, ISeoTandilServices.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ISeoTandilServices
     */
    @WebEndpoint(name = "SeoTandilServicesPort")
    public ISeoTandilServices getSeoTandilServicesPort(WebServiceFeature... features) {
        return super.getPort(SeoTandilServicesPort, ISeoTandilServices.class, features);
    }

}
